# Generated by Django 5.2.15 on 2026-06-12 21:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_clinica_token_captacion'),
        ('pacientes', '0003_atencion_diagnostico_atencion_frecuencia_cardiaca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=160)),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('anulado', 'Anulado')], default='pendiente', max_length=12)),
                ('medio_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='', max_length=15)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='pacientes.atencion')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='pacientes.cita')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='finanzas.servicio')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['clinica', 'activo'], name='finanzas_se_clinica_dbd6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['clinica', 'estado'], name='finanzas_co_clinica_6f3017_idx'),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['clinica', 'fecha'], name='finanzas_co_clinica_1911a9_idx'),
        ),
    ]
