# Generated by Django 5.2.15 on 2026-06-13 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clinica_token_captacion'),
        ('finanzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('concepto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('insumos', 'Insumos / materiales'), ('sueldos', 'Sueldos / honorarios'), ('alquiler', 'Alquiler / servicios'), ('equipos', 'Equipos'), ('marketing', 'Marketing / pauta'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='', max_length=15)),
                ('proveedor', models.CharField(blank=True, default='', max_length=160)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['clinica', 'fecha'], name='finanzas_eg_clinica_bcd879_idx')],
            },
        ),
    ]
