# Generated by Django 5.2.15 on 2026-06-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_egreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='comprobante_numero',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cobro',
            name='comprobante_tipo',
            field=models.CharField(blank=True, choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('recibo', 'Recibo por honorarios'), ('nota_venta', 'Nota de venta')], default='', max_length=12),
        ),
    ]
