# Generated by Django 5.2.15 on 2026-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_soto_sincronizado'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paquete',
            new_name='finanzas_pa_clinica_89a334_idx',
            old_name='finanzas_pa_clinica_2b6c0e_idx',
        ),
        migrations.AlterField(
            model_name='cobro',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], default='', max_length=15),
        ),
    ]
