# Generated by Django 5.2.15 on 2026-07-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_medio_mercado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='monto_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='monto de referencia (liquidación)'),
        ),
    ]
