# Generated by Django 5.2.15 on 2026-08-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_servicio_reservable_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('otro', 'Otro')], default='', max_length=15),
        ),
    ]
