# Generated by Django 5.2.15 on 2026-06-12 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_clinica_whatsapp_instance'),
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('fuente', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('referido', 'Referido'), ('whatsapp', 'WhatsApp'), ('web', 'Web'), ('convenio', 'Convenio'), ('otro', 'Otro')], default='instagram', max_length=20)),
                ('es_pauta', models.BooleanField(default=False, verbose_name='¿Vino de pauta (anuncio pagado)?')),
                ('campania', models.CharField(blank=True, max_length=120, verbose_name='campaña')),
                ('especialidad', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('agendado', 'Cita agendada'), ('ganado', 'Inició tratamiento'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('motivo_perdida', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('medico', models.ForeignKey(blank=True, help_text='Doctor de la pauta / al que se asigna el lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, help_text='Se enlaza cuando el lead se convierte en paciente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'estado'], name='leads_lead_clinica_b85742_idx')],
            },
        ),
    ]
