# Generated by Django 5.2.15 on 2026-06-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reportesemanal'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='es_pareja',
            field=models.BooleanField(default=False, verbose_name='¿Consulta de pareja?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='fecha en que inició proceso'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_consulta',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de la consulta'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sede',
            field=models.CharField(blank=True, choices=[('piura', 'Piura'), ('lima', 'Lima')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('agendado', 'Consulta agendada'), ('no_realizada', 'Consulta no realizada'), ('evaluando', 'Evaluando inicio'), ('pendiente_pago', 'Pendiente de pago'), ('ganado', 'Inició proceso'), ('perdido', 'Perdido')], default='nuevo', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fuente',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('referido', 'Referido'), ('whatsapp', 'WhatsApp directo'), ('bot', 'Bot / Chatbot'), ('web', 'Web'), ('agendapro', 'AgendaPro web'), ('derivado', 'Derivado de otra sede'), ('linkedin', 'LinkedIn'), ('convenio', 'Convenio'), ('otro', 'Otro')], default='instagram', max_length=20),
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(help_text='Título del anuncio o publicación.', max_length=200)),
                ('link', models.URLField(blank=True, default='')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('otro', 'Otro')], default='instagram', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='anuncio',
            field=models.ForeignKey(blank=True, help_text='Anuncio/publicación que atrajo al lead (si vino de pauta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.anuncio'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['clinica', 'activo'], name='leads_anunc_clinica_88ccd7_idx'),
        ),
    ]
