# Generated by Django 5.2.15 on 2026-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_es_pareja_lead_fecha_cierre_lead_fecha_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='motivo_consulta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='objeciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='resumen_conversacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('adultos', 'Adultos'), ('ninos', 'Niños'), ('adolescentes', 'Adolescentes'), ('pareja', 'Pareja'), ('familia', 'Familia'), ('lenguaje', 'Lenguaje'), ('evaluacion', 'Evaluación psicológica'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='ultimo_contacto',
            field=models.DateTimeField(blank=True, null=True, verbose_name='último seguimiento'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fuente',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('referido', 'Referido'), ('whatsapp', 'WhatsApp directo'), ('bot', 'Bot / Chatbot'), ('web', 'Web'), ('agendapro', 'AgendaPro web'), ('derivado', 'Derivado de otra sede'), ('linkedin', 'LinkedIn'), ('convenio', 'Convenio'), ('meta_ads', 'Meta Ads'), ('google', 'Google'), ('referido_paciente', 'Referido por paciente'), ('referido_psicologo', 'Referido por psicólogo'), ('organico', 'Orgánico'), ('otro', 'Otro')], default='instagram', max_length=20),
        ),
    ]
