# Generated by Django 5.2.15 on 2026-07-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_fuente_otro_lead_agendo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='recontacto_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='recontactar el'),
        ),
        migrations.AddField(
            model_name='lead',
            name='seguimiento_frecuencia',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('seguimiento', 'En seguimiento'), ('recontacto', 'Recontactar'), ('agendado', 'Consulta agendada'), ('no_realizada', 'Consulta no realizada'), ('evaluando', 'Evaluando inicio'), ('pendiente_pago', 'Pendiente de pago'), ('ganado', 'Inició proceso'), ('perdido', 'Perdido')], default='nuevo', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fuente',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('referido', 'Referido'), ('whatsapp', 'WhatsApp directo'), ('bot', 'Bot / Chatbot'), ('web', 'Web'), ('agendapro', 'Sistema (agenda directa)'), ('derivado', 'Derivado de otra sede'), ('linkedin', 'LinkedIn'), ('convenio', 'Convenio'), ('alianza', 'Alianza'), ('meta_ads', 'Meta Ads'), ('google', 'Google'), ('referido_paciente', 'Referido por paciente'), ('referido_psicologo', 'Referido por psicólogo'), ('organico', 'Orgánico'), ('otro', 'Otro')], default='instagram', max_length=20),
        ),
    ]
