# Generated by Django 5.2.15 on 2026-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_seguimiento_recontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='sede',
            field=models.CharField(blank=True, choices=[('lima', 'Lima'), ('piura', 'Piura'), ('ambas', 'Todas las sedes')], default='', help_text='Sede a la que apunta la pauta.', max_length=10),
        ),
    ]
