# Generated by Django 5.2.15 on 2026-07-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_subfuente_alter_lead_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='correo'),
        ),
    ]
