# Generated by Django 5.2.15 on 2026-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fuente',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('referido', 'Referido'), ('whatsapp', 'WhatsApp directo'), ('instagram_directo', 'Instagram directo'), ('bot', 'Bot / Chatbot'), ('web', 'Web'), ('agendapro', 'Sistema (agenda directa)'), ('derivado', 'Derivado de otra sede'), ('linkedin', 'LinkedIn'), ('convenio', 'Convenio'), ('alianza', 'Alianza'), ('meta_ads', 'Meta Ads'), ('google', 'Google'), ('referido_paciente', 'Referido por paciente'), ('referido_psicologo', 'Referido por psicólogo'), ('organico', 'Orgánico'), ('tiktok_ads', 'TikTok Ads'), ('facebook_ads', 'Facebook Ads'), ('otro', 'Otro')], default='instagram', max_length=20),
        ),
    ]
