# Generated by Django 5.2.15 on 2026-07-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_hora_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('seguimiento', 'En seguimiento'), ('recontacto', 'Recontactar'), ('agendado', 'Consulta agendada'), ('agendo_no_pago', 'Agendó, no pagó'), ('agendo_espera_pago', 'Agendó, esperando pago'), ('no_realizada', 'Consulta no realizada'), ('evaluando', 'Evaluando inicio'), ('pendiente_pago', 'Pendiente de pago'), ('ganado', 'Inició proceso'), ('perdido', 'Perdido')], default='nuevo', max_length=20),
        ),
    ]
