# Generated by Django 5.2.15 on 2026-08-14 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_lead_estado'),
        ('pacientes', '0029_cita_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita de la consulta agendada, creada desde el lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='pacientes.cita'),
        ),
    ]
