# Generated by Django 5.2.15 on 2026-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='enlace_consulta',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='enlace de la videollamada'),
        ),
        migrations.AddField(
            model_name='lead',
            name='modalidad_consulta',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='', max_length=12, verbose_name='modalidad de la consulta'),
        ),
    ]
