# Generated by Django 5.2.15 on 2026-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_enlace_consulta_lead_modalidad_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacto_nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del responsable'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacto_parentesco',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacto_telefono',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Teléfono del responsable'),
        ),
    ]
