# Generated by Django 5.2.15 on 2026-09-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_contacto_nombre_lead_contacto_parentesco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='origen_canal',
            field=models.CharField(blank=True, default='', help_text='De qué plataforma vino (google, instagram, meta…). Se llena solo.', max_length=80, verbose_name='canal de origen'),
        ),
        migrations.AddField(
            model_name='lead',
            name='origen_contenido',
            field=models.CharField(blank=True, default='', help_text='Qué anuncio o versión concreta trajo la visita.', max_length=120, verbose_name='anuncio / variante'),
        ),
        migrations.AddField(
            model_name='lead',
            name='origen_detalle',
            field=models.JSONField(blank=True, default=dict, help_text='Lo que no tiene columna propia: término, ids de clic, página de entrada y sitio que refirió.', verbose_name='detalle del origen'),
        ),
        migrations.AddField(
            model_name='lead',
            name='origen_medio',
            field=models.CharField(blank=True, default='', help_text='Cómo llegó desde ahí (cpc, organic, social…). Se llena solo.', max_length=80, verbose_name='medio de origen'),
        ),
    ]
