# Generated by Django 5.2.15 on 2026-09-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('leads', '0017_origen_de_la_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visita', 'Vio una página'), ('clic_reservar', 'Hizo clic en reservar'), ('abre_agenda', 'Abrió el formulario de reserva')], max_length=20, verbose_name='paso')),
                ('ruta', models.CharField(blank=True, default='', max_length=200, verbose_name='página')),
                ('canal', models.CharField(blank=True, default='', max_length=80, verbose_name='canal de origen')),
                ('medio', models.CharField(blank=True, default='', max_length=80, verbose_name='medio de origen')),
                ('campania', models.CharField(blank=True, default='', max_length=120, verbose_name='campaña')),
                ('sesion', models.CharField(blank=True, default='', max_length=32, verbose_name='visita (efímero)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Evento del sitio',
                'verbose_name_plural': 'Eventos del sitio',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'creado_en'], name='leads_event_clinica_68558d_idx'), models.Index(fields=['clinica', 'tipo', 'creado_en'], name='leads_event_clinica_3bb564_idx')],
            },
        ),
    ]
