# Generated by Django 5.2.15 on 2026-09-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('leads', '0018_eventositio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.CharField(max_length=200, verbose_name='institución educativa')),
                ('responsable', models.CharField(max_length=200, verbose_name='persona responsable')),
                ('cargo', models.CharField(blank=True, default='', max_length=120)),
                ('ciudad', models.CharField(blank=True, default='', max_length=120)),
                ('estudiantes', models.PositiveIntegerField(blank=True, null=True, verbose_name='estudiantes aproximados')),
                ('nivel', models.CharField(blank=True, choices=[('secundaria', 'Secundaria'), ('primaria', 'Primaria'), ('ambos', 'Primaria y secundaria'), ('otro', 'Otro')], default='', max_length=12)),
                ('interes', models.CharField(blank=True, choices=[('tamizaje', 'Tamizaje preventivo (Faro)'), ('evaluacion', 'Evaluación de casos puntuales'), ('talleres', 'Talleres y capacitación'), ('programa', 'Programa de bienestar escolar'), ('no_sabe', 'Aún no lo tiene claro')], default='', max_length=12, verbose_name='qué busca')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactada', 'Contactada'), ('reunion', 'Reunión agendada'), ('propuesta', 'Propuesta enviada'), ('ganada', 'Convenio firmado'), ('perdida', 'Perdida')], default='nueva', max_length=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Solicitud de institución educativa',
                'verbose_name_plural': 'Solicitudes de instituciones educativas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'estado'], name='leads_solic_clinica_85980f_idx')],
            },
        ),
    ]
