# Generated by Django 5.2.15 on 2026-07-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_recurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(help_text='Ej: Consultorio 1', max_length=80)),
                ('sede', models.CharField(choices=[('lima', 'Lima'), ('piura', 'Piura')], max_length=10)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'ordering': ['sede', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InteresadoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=160)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('profesion', models.CharField(blank=True, default='', max_length=160, verbose_name='profesión / especialidad')),
                ('sede_interes', models.CharField(blank=True, choices=[('lima', 'Lima'), ('piura', 'Piura')], default='', max_length=10)),
                ('estado', models.CharField(choices=[('interesado', 'Interesado'), ('visita', 'Visita'), ('negociacion', 'Negociación'), ('activo', 'Activo'), ('descartado', 'Descartado')], default='interesado', max_length=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('proximo_seguimiento', models.DateField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interesados_alquiler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interesado en alquiler',
                'verbose_name_plural': 'Interesados en alquiler',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ContratoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=160)),
                ('profesion', models.CharField(blank=True, default='', max_length=160, verbose_name='profesión / especialidad')),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('por_horas', 'Por horas (flexible)'), ('fijo', 'Horario fijo (semanal)')], default='por_horas', max_length=10)),
                ('plan', models.CharField(blank=True, default='', help_text='Nombre del plan del dossier: Plan Flexible 2, Inicio, Full…', max_length=80)),
                ('horas_contratadas', models.DecimalField(decimal_places=1, default=0, help_text='Horas del plan (al mes si es flexible; a la semana si es fijo).', max_digits=6)),
                ('horario_semanal', models.CharField(blank=True, default='', help_text="Si es horario fijo: p. ej. 'Lun y Mié 10:00-12:00'.", max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='activo', max_length=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='espacios.consultorio')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_alquiler', to=settings.AUTH_USER_MODEL)),
                ('interesado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='espacios.interesadoalquiler')),
            ],
            options={
                'verbose_name': 'Contrato de alquiler',
                'verbose_name_plural': 'Contratos de alquiler',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PagoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('medio_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='', max_length=15)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('horas_cubiertas', models.DecimalField(decimal_places=1, default=0, help_text='Cuántas horas de alquiler cubre este pago.', max_digits=6)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='espacios.contratoalquiler')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_alquiler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de alquiler',
                'verbose_name_plural': 'Pagos de alquiler',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('externo', 'Profesional externo (alquiler)'), ('conversemos', 'Conversemos / Itaca')], default='externo', max_length=12)),
                ('ocupante', models.CharField(blank=True, default='', help_text='Nombre del profesional que ocupa el espacio.', max_length=160)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='espacios.consultorio')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='espacios.contratoalquiler')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_espacio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de espacio',
                'verbose_name_plural': 'Reservas de espacio',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='consultorio',
            index=models.Index(fields=['clinica', 'sede', 'activo'], name='espacios_co_clinica_2830a9_idx'),
        ),
        migrations.AddIndex(
            model_name='interesadoalquiler',
            index=models.Index(fields=['clinica', 'estado'], name='espacios_in_clinica_9e6993_idx'),
        ),
        migrations.AddIndex(
            model_name='contratoalquiler',
            index=models.Index(fields=['clinica', 'estado'], name='espacios_co_clinica_b7eaed_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoalquiler',
            index=models.Index(fields=['clinica', 'estado'], name='espacios_pa_clinica_254241_idx'),
        ),
        migrations.AddIndex(
            model_name='reservaespacio',
            index=models.Index(fields=['clinica', 'fecha'], name='espacios_re_clinica_2219a8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservaespacio',
            index=models.Index(fields=['consultorio', 'fecha'], name='espacios_re_consult_5d8b03_idx'),
        ),
    ]
