# Generated by Django 5.2.15 on 2026-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Identificador para URL / subdominio.', unique=True)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('zona_horaria', models.CharField(default='America/Lima', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['nombre'],
            },
        ),
    ]
