# Generated by Django 5.2.15 on 2026-06-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='whatsapp_instance',
            field=models.CharField(blank=True, help_text='Instancia de Evolution API para el WhatsApp de esta clínica. Si se deja vacío, usa EVOLUTION_INSTANCE del entorno.', max_length=120),
        ),
    ]
