# Generated by Django 5.2.15 on 2026-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinica_whatsapp_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='token_captacion',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
