# Generated by Django 5.2.15 on 2026-06-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clinica_token_captacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sede', models.CharField(choices=[('piura', 'Piura'), ('lima', 'Lima')], max_length=10)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(help_text='1 = Enero … 12 = Diciembre')),
                ('invertido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='invertido en pauta (S/)')),
                ('mensajes', models.PositiveIntegerField(default=0)),
                ('citas_nuevas', models.PositiveIntegerField(default=0)),
                ('pacientes', models.PositiveIntegerField(default=0, verbose_name='pacientes/clientes nuevos')),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Métrica mensual',
                'verbose_name_plural': 'Métricas mensuales',
                'ordering': ['-anio', '-mes', 'sede'],
                'indexes': [models.Index(fields=['clinica', 'anio'], name='core_metric_clinica_18f382_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinica', 'sede', 'anio', 'mes'), name='uniq_metrica_sede_mes')],
            },
        ),
    ]
