# Generated by Django 5.2.15 on 2026-06-18 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_metricamensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('semana', models.PositiveSmallIntegerField(help_text='N° de semana del mes (1-5)')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('novedades', models.TextField(blank=True, default='')),
                ('fact_lima', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fact_piura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meta_min_sede', models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='meta mínima por sede (S/)')),
                ('meta_ideal_sede', models.DecimalField(decimal_places=2, default=30000, max_digits=10, verbose_name='meta ideal por sede (S/)')),
                ('proy_lima', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='proyección cierre Lima (S/)')),
                ('proy_piura', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='proyección cierre Piura (S/)')),
                ('leads_lima', models.PositiveIntegerField(default=0)),
                ('leads_piura', models.PositiveIntegerField(default=0)),
                ('consultas_agendadas', models.PositiveIntegerField(default=0)),
                ('pacientes_iniciaron', models.PositiveIntegerField(default=0)),
                ('videos_publicados', models.PositiveIntegerField(default=0)),
                ('videos_planificados', models.PositiveIntegerField(default=0)),
                ('invertido_lima', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invertido_piura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pac_activos_lima', models.PositiveIntegerField(default=0)),
                ('pac_activos_piura', models.PositiveIntegerField(default=0)),
                ('retencion_lima', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='retención S3+ Lima (%)')),
                ('retencion_piura', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='retención S3+ Piura (%)')),
                ('sin_proxima', models.PositiveIntegerField(default=0, verbose_name='pacientes sin próxima sesión')),
                ('ocupacion_lima', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ocupación agenda Lima (%)')),
                ('ocupacion_piura', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ocupación agenda Piura (%)')),
                ('decisiones', models.TextField(blank=True, default='', help_text='Decisiones requeridas esta semana.')),
                ('compromisos', models.TextField(blank=True, default='')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Reporte semanal',
                'verbose_name_plural': 'Reportes semanales',
                'ordering': ['-anio', '-mes', '-semana'],
                'constraints': [models.UniqueConstraint(fields=('clinica', 'anio', 'mes', 'semana'), name='uniq_reporte_semana')],
            },
        ),
    ]
