# Generated by Django 5.2.15 on 2026-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reportesemanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricamensual',
            name='leads',
            field=models.PositiveIntegerField(default=0, verbose_name='leads calificados'),
        ),
    ]
