# Generated by Django 5.2.15 on 2026-06-26 18:39

import django.db.models.deletion
from django.db import migrations, models


def copiar_numero_existente(apps, schema_editor):
    """Si una clínica ya tenía un número configurado en los campos viejos de
    Clinica, se copia como su primer NumeroWhatsapp para no perder la conexión."""
    Clinica = apps.get_model("core", "Clinica")
    NumeroWhatsapp = apps.get_model("core", "NumeroWhatsapp")
    for c in Clinica.objects.all():
        if c.wa_phone_number_id or c.wa_access_token:
            NumeroWhatsapp.objects.create(
                clinica=c,
                sede="",  # el número antiguo no tenía sede; el admin la asigna
                wa_phone_number_id=c.wa_phone_number_id,
                wa_access_token=c.wa_access_token,
                wa_waba_id=c.wa_waba_id,
                activo=True,
            )


def revertir(apps, schema_editor):
    NumeroWhatsapp = apps.get_model("core", "NumeroWhatsapp")
    NumeroWhatsapp.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clinica_whatsapp_cloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sede', models.CharField(blank=True, choices=[('lima', 'Lima'), ('piura', 'Piura'), ('ambas', 'Ambas sedes')], default='', max_length=10)),
                ('wa_phone_number_id', models.CharField(blank=True, default='', max_length=40, verbose_name='Phone Number ID')),
                ('wa_access_token', models.TextField(blank=True, default='', verbose_name='Access Token')),
                ('wa_waba_id', models.CharField(blank=True, default='', max_length=40, verbose_name='WABA ID')),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Número de WhatsApp',
                'verbose_name_plural': 'Números de WhatsApp',
                'ordering': ['sede', 'id'],
            },
        ),
        migrations.RunPython(copiar_numero_existente, revertir),
    ]
