# Generated by Django 5.2.15 on 2026-07-01 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_numerowhatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(blank=True, default='', max_length=120, verbose_name='tema / área')),
                ('mensaje', models.TextField()),
                ('contexto', models.TextField(blank=True, default='')),
                ('desea', models.CharField(blank=True, choices=[('tener_en_cuenta', 'Que se tenga en cuenta'), ('revisar_proceso', 'Que se revise un proceso'), ('me_contacten', 'Que alguien me contacte'), ('solo_observacion', 'Que solo quede como observación'), ('conversar', 'Que se converse con alguien')], default='', max_length=20)),
                ('contacto', models.CharField(blank=True, default='', max_length=200)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('vista', 'Vista'), ('atendida', 'Atendida')], default='nueva', max_length=10)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'ordering': ['-creado_en'],
            },
        ),
    ]
