# Generated by Django 5.2.15 on 2026-07-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sugerencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('herramienta', 'Herramienta para pacientes'), ('tip', 'Tip para el psicólogo'), ('recordatorio', 'Recordatorio de gerencia')], default='herramienta', max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, default='', help_text='Ej: Ansiedad, Pareja, Onboarding…', max_length=120)),
                ('fijado', models.BooleanField(default=False, help_text='Los recordatorios fijados salen primero en el inicio.')),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-fijado', '-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'tipo', 'activo'], name='core_recurs_clinica_f0d618_idx')],
            },
        ),
    ]
