# Generated by Django 5.2.15 on 2026-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='texto_consentimiento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinica',
            name='texto_politicas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
