# Generated by Django 5.2.15 on 2026-07-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_clinica_texto_consentimiento_clinica_texto_politicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='meta_ideal_mes',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=10, verbose_name='meta ideal del mes (S/)'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='meta_min_mes',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10, verbose_name='meta mínima del mes (S/)'),
        ),
    ]
