# Generated by Django 5.2.15 on 2026-07-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clinica_meta_ideal_mes_clinica_meta_min_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('herramienta', 'Herramienta para pacientes'), ('terapeuta', 'Herramienta para el terapeuta'), ('manual', 'Manual o guía'), ('tip', 'Autocuidado del terapeuta'), ('recordatorio', 'Recordatorio de gerencia')], default='herramienta', max_length=15),
        ),
    ]
