# Generated by Django 5.2.15 on 2026-07-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_recurso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='metas_sede',
            field=models.JSONField(blank=True, default=dict, verbose_name='metas por sede'),
        ),
    ]
