# Generated by Django 5.2.15 on 2026-07-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clinica_metas_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='mof',
            field=models.TextField(blank=True, default='', verbose_name='MOF'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='pilares',
            field=models.TextField(blank=True, default='', verbose_name='Pilares Itaca'),
        ),
    ]
