# Generated by Django 5.2.15 on 2026-07-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_mof_pilares'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='mentalidad',
            field=models.JSONField(blank=True, default=dict, verbose_name='Mentalidad Ítaca'),
        ),
    ]
