# Generated by Django 5.2.15 on 2026-09-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_clinica_gamificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='token_webhook_evolution',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InstanciaEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sede', models.CharField(blank=True, choices=[('lima', 'Lima'), ('piura', 'Piura'), ('ambas', 'Ambas sedes')], default='', max_length=10)),
                ('nombre_instancia', models.CharField(help_text='Nombre EXACTO de la instancia en Evolution API (ej. conversemoslima).', max_length=120, verbose_name='Instancia de Evolution')),
                ('activo', models.BooleanField(default=True)),
                ('respuestas_automaticas', models.BooleanField(default=False, help_text='Déjalo apagado: el número oficial lo atiende una persona.', verbose_name='Responder automáticamente')),
                ('ultimo_estado', models.CharField(blank=True, default='', max_length=30)),
                ('ultimo_evento_en', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Instancia de Evolution',
                'verbose_name_plural': 'Instancias de Evolution',
                'ordering': ['sede', 'id'],
                'indexes': [models.Index(fields=['clinica', 'sede', 'activo'], name='core_instan_clinica_ef82b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinica', 'nombre_instancia'), name='uniq_evolution_instancia'), models.UniqueConstraint(condition=models.Q(('activo', True), ('sede__in', ['lima', 'piura'])), fields=('clinica', 'sede'), name='uniq_evolution_sede_activa')],
            },
        ),
    ]
