# Generated by Django 5.2.15 on 2026-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_clinica_token_webhook_evolution_instanciaevolution'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instanciaevolution',
            name='uniq_evolution_sede_activa',
        ),
        migrations.AddField(
            model_name='instanciaevolution',
            name='entorno',
            field=models.CharField(choices=[('oficial', 'Línea oficial de sede'), ('prueba', 'Ambiente de pruebas')], default='oficial', max_length=10),
        ),
        migrations.AddField(
            model_name='instanciaevolution',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='instanciaevolution',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('entorno', 'oficial'), ('sede__in', ['lima', 'piura'])), fields=('clinica', 'sede'), name='uniq_evolution_sede_activa'),
        ),
    ]
