# Generated by Django 5.2.15 on 2026-10-01 04:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('faro', '0007_respuesta_ciber_rol'),
        ('leads', '0019_solicitudinstitucional'),
        ('pacientes', '0038_paciente_tutor_correo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('SERVICE', 'Servicio solicitado'), ('CARE', 'Acompañamiento asistencial'), ('MARKETING', 'Comunicación comercial')], max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('asunto', models.CharField(max_length=200)),
                ('preencabezado', models.CharField(blank=True, default='', max_length=200)),
                ('cuerpo_html', models.TextField()),
                ('cuerpo_texto', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('incluye_preferencias', models.BooleanField(default=False)),
                ('requiere_baja_un_clic', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de correo',
                'verbose_name_plural': 'Plantillas de correo',
                'ordering': ['clave', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CorreoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('es_tutor', models.BooleanField(default=False, help_text='La fila es del padre, madre o tutor del paciente, no del paciente.', verbose_name='es del tutor')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('categoria', models.CharField(choices=[('SERVICE', 'Servicio solicitado'), ('CARE', 'Acompañamiento asistencial'), ('MARKETING', 'Comunicación comercial')], max_length=10)),
                ('destinatario_correo', models.EmailField(blank=True, default='', max_length=254)),
                ('asunto', models.CharField(blank=True, default='', max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIANDO', 'Enviando'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('REBOTE_SUAVE', 'Rebote temporal'), ('REBOTE_DURO', 'Rebote permanente'), ('BLOQUEADO', 'Bloqueado por el proveedor'), ('SPAM', 'Marcado como spam'), ('DADO_DE_BAJA', 'Se dio de baja'), ('CANCELADO_ELEGIBILIDAD', 'No se envió (no elegible)'), ('ERROR', 'Error')], default='PENDIENTE', max_length=24)),
                ('brevo_message_id', models.CharField(blank=True, default='', max_length=200)),
                ('origen', models.CharField(blank=True, default='', max_length=40)),
                ('clave_idempotencia', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('error_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('error_detalle', models.CharField(blank=True, default='', max_length=300)),
                ('envio_iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_evento_en', models.DateTimeField(blank=True, null=True)),
                ('autorizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='faro.autorizacion', verbose_name='autorización de Faro (apoderado)')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.lead')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pacientes.paciente')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='correo.plantillacorreo')),
            ],
            options={
                'verbose_name': 'Correo enviado',
                'verbose_name_plural': 'Bitácora de correos',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('es_tutor', models.BooleanField(default=False, help_text='La fila es del padre, madre o tutor del paciente, no del paciente.', verbose_name='es del tutor')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('marketing_bloqueado', models.BooleanField(default=False)),
                ('marketing_bloqueado_en', models.DateTimeField(blank=True, null=True)),
                ('rebote_duro', models.BooleanField(default=False)),
                ('rebote_duro_en', models.DateTimeField(blank=True, null=True)),
                ('marcado_spam', models.BooleanField(default=False)),
                ('marcado_spam_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autorizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='faro.autorizacion', verbose_name='autorización de Faro (apoderado)')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.lead')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Preferencia de correo',
                'verbose_name_plural': 'Preferencias de correo',
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('es_tutor', models.BooleanField(default=False, help_text='La fila es del padre, madre o tutor del paciente, no del paciente.', verbose_name='es del tutor')),
                ('canal', models.CharField(choices=[('CORREO', 'Correo electrónico')], default='CORREO', max_length=10)),
                ('finalidad', models.CharField(choices=[('MARKETING', 'Comunicaciones comerciales'), ('ASISTENCIAL', 'Comunicaciones asistenciales')], max_length=12)),
                ('estado', models.CharField(choices=[('OTORGADO', 'Otorgado'), ('REVOCADO', 'Revocado')], max_length=10)),
                ('origen', models.CharField(choices=[('RESERVA_WEB', 'Reserva web'), ('AYUDA_ELEGIR', 'Formulario «Ayúdenme a elegir»'), ('AUTORIZACION_FARO', 'Autorización de Faro'), ('CONSENTIMIENTO_INFORMADO', 'Consentimiento informado'), ('PANEL_WHATSAPP', 'Registrado en el panel (WhatsApp)'), ('PANEL_PRESENCIAL', 'Registrado en el panel (presencial)'), ('PREFERENCIAS_WEB', 'Centro de preferencias'), ('BAJA_UN_CLIC', 'Baja de un clic'), ('WEBHOOK_PROVEEDOR', 'Aviso del proveedor de correo')], max_length=30)),
                ('version_texto', models.CharField(blank=True, default='', max_length=40)),
                ('texto_aceptado', models.TextField(blank=True, default='')),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('autorizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='faro.autorizacion', verbose_name='autorización de Faro (apoderado)')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('consentimiento_previo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siguientes', to='correo.consentimientocomunicacion')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.lead')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_correo_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento de comunicación',
                'verbose_name_plural': 'Consentimientos de comunicación',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['paciente', 'es_tutor', 'finalidad', 'fecha'], name='cc_pac_idx'), models.Index(fields=['lead', 'finalidad', 'fecha'], name='cc_lead_idx'), models.Index(fields=['autorizacion', 'finalidad', 'fecha'], name='cc_aut_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('paciente__isnull', False), models.Q(('lead__isnull', False), _negated=True), models.Q(('autorizacion__isnull', False), _negated=True)), models.Q(models.Q(('paciente__isnull', False), _negated=True), ('lead__isnull', False), models.Q(('autorizacion__isnull', False), _negated=True)), models.Q(models.Q(('paciente__isnull', False), _negated=True), models.Q(('lead__isnull', False), _negated=True), ('autorizacion__isnull', False)), _connector='OR'), name='cc_una_identidad'), models.CheckConstraint(condition=models.Q(('es_tutor', False), ('paciente__isnull', False), _connector='OR'), name='cc_tutor_con_paciente')],
            },
        ),
        migrations.CreateModel(
            name='EnvioProgramadoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('es_tutor', models.BooleanField(default=False, help_text='La fila es del padre, madre o tutor del paciente, no del paciente.', verbose_name='es del tutor')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plantilla_clave', models.CharField(max_length=60)),
                ('ejecutar_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=12)),
                ('clave_idempotencia', models.CharField(max_length=120, unique=True)),
                ('grupo', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('error_detalle', models.CharField(blank=True, default='', max_length=300)),
                ('cancelado_motivo', models.CharField(blank=True, default='', max_length=60)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autorizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='faro.autorizacion', verbose_name='autorización de Faro (apoderado)')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('correo_enviado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='correo.correoenviado')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.lead')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Envío programado',
                'verbose_name_plural': 'Envíos programados',
                'ordering': ['ejecutar_en', 'id'],
                'indexes': [models.Index(fields=['paciente', 'es_tutor', 'estado'], name='epc_pac_idx'), models.Index(fields=['lead', 'estado'], name='epc_lead_idx'), models.Index(fields=['autorizacion', 'estado'], name='epc_aut_idx'), models.Index(fields=['estado', 'ejecutar_en'], name='epc_estado_ejecutar_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('paciente__isnull', False), models.Q(('lead__isnull', False), _negated=True), models.Q(('autorizacion__isnull', False), _negated=True)), models.Q(models.Q(('paciente__isnull', False), _negated=True), ('lead__isnull', False), models.Q(('autorizacion__isnull', False), _negated=True)), models.Q(models.Q(('paciente__isnull', False), _negated=True), models.Q(('lead__isnull', False), _negated=True), ('autorizacion__isnull', False)), _connector='OR'), name='epc_una_identidad'), models.CheckConstraint(condition=models.Q(('es_tutor', False), ('paciente__isnull', False), _connector='OR'), name='epc_tutor_con_paciente')],
            },
        ),
        migrations.CreateModel(
            name='EventoCorreoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('REBOTE_SUAVE', 'Rebote temporal'), ('REBOTE_DURO', 'Rebote permanente'), ('BLOQUEADO', 'Bloqueado'), ('CLIC', 'Clic'), ('BAJA', 'Baja'), ('SPAM', 'Spam'), ('ERROR', 'Error')], max_length=14)),
                ('tipo_original', models.CharField(blank=True, default='', max_length=40)),
                ('brevo_event_id', models.CharField(max_length=200, unique=True)),
                ('brevo_message_id', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('correo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='correo.correoenviado')),
            ],
            options={
                'verbose_name': 'Evento del proveedor de correo',
                'verbose_name_plural': 'Eventos del proveedor de correo',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['brevo_message_id'], name='ecp_msgid_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='plantillacorreo',
            constraint=models.UniqueConstraint(fields=('clave', 'version'), name='plantilla_correo_clave_version'),
        ),
        migrations.AddIndex(
            model_name='correoenviado',
            index=models.Index(fields=['paciente', 'es_tutor', 'creado_en'], name='ce_pac_idx'),
        ),
        migrations.AddIndex(
            model_name='correoenviado',
            index=models.Index(fields=['lead', 'creado_en'], name='ce_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='correoenviado',
            index=models.Index(fields=['autorizacion', 'creado_en'], name='ce_aut_idx'),
        ),
        migrations.AddIndex(
            model_name='correoenviado',
            index=models.Index(fields=['brevo_message_id'], name='ce_msgid_idx'),
        ),
        migrations.AddIndex(
            model_name='correoenviado',
            index=models.Index(fields=['estado', 'creado_en'], name='ce_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='correoenviado',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paciente__isnull', False), models.Q(('lead__isnull', False), _negated=True), models.Q(('autorizacion__isnull', False), _negated=True)), models.Q(models.Q(('paciente__isnull', False), _negated=True), ('lead__isnull', False), models.Q(('autorizacion__isnull', False), _negated=True)), models.Q(models.Q(('paciente__isnull', False), _negated=True), models.Q(('lead__isnull', False), _negated=True), ('autorizacion__isnull', False)), _connector='OR'), name='ce_una_identidad'),
        ),
        migrations.AddConstraint(
            model_name='correoenviado',
            constraint=models.CheckConstraint(condition=models.Q(('es_tutor', False), ('paciente__isnull', False), _connector='OR'), name='ce_tutor_con_paciente'),
        ),
        migrations.AddIndex(
            model_name='preferenciacorreo',
            index=models.Index(fields=['paciente', 'es_tutor'], name='pc_pac_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciacorreo',
            index=models.Index(fields=['lead'], name='pc_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciacorreo',
            index=models.Index(fields=['autorizacion'], name='pc_aut_idx'),
        ),
        migrations.AddConstraint(
            model_name='preferenciacorreo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paciente__isnull', False), models.Q(('lead__isnull', False), _negated=True), models.Q(('autorizacion__isnull', False), _negated=True)), models.Q(models.Q(('paciente__isnull', False), _negated=True), ('lead__isnull', False), models.Q(('autorizacion__isnull', False), _negated=True)), models.Q(models.Q(('paciente__isnull', False), _negated=True), models.Q(('lead__isnull', False), _negated=True), ('autorizacion__isnull', False)), _connector='OR'), name='pc_una_identidad'),
        ),
        migrations.AddConstraint(
            model_name='preferenciacorreo',
            constraint=models.CheckConstraint(condition=models.Q(('es_tutor', False), ('paciente__isnull', False), _connector='OR'), name='pc_tutor_con_paciente'),
        ),
    ]
