# Generated by Django 5.2.15 on 2026-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0002_plantillas_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciacorreo',
            name='rebote_duro_correo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
