# Generated by Django 5.2.15 on 2026-06-12 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'medico'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atencion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='pacientes.cita'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='pacientes.paciente'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['clinica', 'nombre'], name='pacientes_p_clinica_ae6345_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['clinica', 'inicio'], name='pacientes_c_clinica_a213e0_idx'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['clinica', 'paciente'], name='pacientes_a_clinica_f3b12d_idx'),
        ),
    ]
