# Generated by Django 5.2.15 on 2026-06-12 18:23

import django.db.models.deletion
import pacientes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinica_whatsapp_instance'),
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='diagnostico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atencion',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (lpm)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='indicaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atencion',
            name='motivo',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='atencion',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='presion_arterial',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Presión arterial'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atencion',
            name='talla',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Talla (cm)'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes',
            field=models.TextField(blank=True, default='', help_text='Enfermedades crónicas, cirugías previas, antecedentes familiares relevantes.'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicacion_habitual',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='nota',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to=pacientes.models.ruta_adjunto)),
                ('nombre', models.CharField(help_text="Nombre o descripción visible (p. ej. 'Ecografía abdominal').", max_length=255)),
                ('tipo', models.CharField(blank=True, default='', help_text='Extensión del archivo.', max_length=40)),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='pacientes.atencion')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='pacientes.paciente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'paciente'], name='pacientes_a_clinica_62bea7_idx')],
            },
        ),
    ]
