# Generated by Django 5.2.15 on 2026-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_atencion_diagnostico_atencion_frecuencia_cardiaca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('dni', 'DNI'), ('ce', 'Carné de extranjería'), ('pasaporte', 'Pasaporte'), ('ruc', 'RUC')], default='dni', max_length=12),
        ),
    ]
