# Generated by Django 5.2.15 on 2026-06-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_direccion_paciente_genero_and_more'),
        ('usuarios', '0004_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='n_sesion',
            field=models.PositiveIntegerField(default=0, verbose_name='N° de sesión actual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='proceso',
            field=models.CharField(blank=True, default='', help_text='Etapa del proceso: consulta, primero, segundo, … o quincenal.', max_length=24),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profesional',
            field=models.ForeignKey(blank=True, help_text='Psicólogo del directorio que atiende a este paciente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='usuarios.profesional'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sede',
            field=models.CharField(blank=True, choices=[('piura', 'Piura'), ('lima', 'Lima')], default='', max_length=10),
        ),
    ]
