# Generated by Django 5.2.15 on 2026-06-18 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reportesemanal'),
        ('pacientes', '0005_paciente_n_sesion_paciente_proceso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('semana', models.PositiveSmallIntegerField(help_text='N° de semana del mes (1-5)')),
                ('n_sesion', models.PositiveIntegerField(default=0)),
                ('proceso', models.CharField(blank=True, default='', max_length=24)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Seguimiento de sesión',
                'verbose_name_plural': 'Seguimientos de sesión',
                'ordering': ['anio', 'mes', 'semana'],
                'indexes': [models.Index(fields=['clinica', 'paciente'], name='pacientes_s_clinica_a56435_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinica', 'paciente', 'anio', 'mes', 'semana'), name='uniq_seg_paciente_semana')],
            },
        ),
    ]
