# Generated by Django 5.2.15 on 2026-06-20 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reportesemanal'),
        ('pacientes', '0006_seguimientosesion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicionAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campo', models.CharField(max_length=40)),
                ('antes', models.TextField(blank=True, default='')),
                ('despues', models.TextField(blank=True, default='')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ediciones', to='pacientes.atencion')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones_atencion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edición de atención',
                'verbose_name_plural': 'Ediciones de atención',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'atencion'], name='pacientes_e_clinica_5a39da_idx')],
            },
        ),
    ]
