# Generated by Django 5.2.15 on 2026-06-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_edicionatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='aspectos_historicos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atencion',
            name='objetivos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atencion',
            name='proximos_pasos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atencion',
            name='puntos_importantes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tipo',
            field=models.CharField(choices=[('evolucion', 'Ficha de evolución'), ('historia', 'Historia clínica')], default='evolucion', max_length=12),
        ),
    ]
