# Generated by Django 5.2.15 on 2026-06-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_atencion_aspectos_historicos_atencion_objetivos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='correo electrónico'),
        ),
    ]
