# Generated by Django 5.2.15 on 2026-06-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='tipo',
            field=models.CharField(choices=[('evolucion', 'Ficha de evolución'), ('historia', 'Historia clínica'), ('continuidad', 'Ficha de continuidad'), ('informe_continuidad', 'Informe de continuidad'), ('informe', 'Informe psicológico'), ('derivacion', 'Derivación'), ('evaluacion', 'Evaluación psicológica'), ('otro', 'Otro documento clínico')], default='evolucion', max_length=20),
        ),
    ]
