# Generated by Django 5.2.15 on 2026-06-24 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_metricamensual_leads'),
        ('pacientes', '0010_alter_atencion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('consentimiento', 'Consentimiento informado'), ('politicas', 'Políticas de atención')], default='consentimiento', max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('texto', models.TextField()),
                ('aceptado', models.BooleanField(default=False)),
                ('aceptado_en', models.DateTimeField(blank=True, null=True)),
                ('firmante_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('firmante_documento', models.CharField(blank=True, default='', max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'paciente'], name='pacientes_c_clinica_7db2a3_idx')],
            },
        ),
    ]
