# Generated by Django 5.2.15 on 2026-06-30 17:09

from django.db import migrations, models


def por_confirmar_a_agendada(apps, schema_editor):
    Cita = apps.get_model("pacientes", "Cita")
    Cita.objects.filter(estado="por_confirmar").update(estado="agendada")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_cita_campos_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('en_espera', 'En espera'), ('pendiente', 'Pendiente'), ('asistio', 'Asistió'), ('no_asistio', 'No asistió'), ('atendida', 'Atendida'), ('reprogramada', 'Reprogramada'), ('cancelada', 'Cancelada'), ('por_confirmar', 'Por confirmar')], default='agendada', max_length=20),
        ),
        migrations.RunPython(por_confirmar_a_agendada, noop),
    ]
