# Generated by Django 5.2.15 on 2026-06-30 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_numerowhatsapp'),
        ('pacientes', '0013_estados_cita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sede', models.CharField(blank=True, choices=[('piura', 'Piura'), ('lima', 'Lima')], default='', max_length=10)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('medico', models.ForeignKey(blank=True, limit_choices_to={'rol': 'medico'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo de agenda',
                'verbose_name_plural': 'Bloqueos de agenda',
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['clinica', 'inicio'], name='pacientes_b_clinica_4e0039_idx')],
            },
        ),
    ]
