# Generated by Django 5.2.15 on 2026-06-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_bloqueo_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tutor_documento',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Documento del tutor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor_nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del tutor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor_parentesco',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor_telefono',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Teléfono del tutor'),
        ),
    ]
