# Generated by Django 5.2.15 on 2026-07-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_paciente_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('esporadico', 'Esporádico')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='paciente',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrido', 'Híbrido')], default='', max_length=12),
        ),
    ]
