# Generated by Django 5.2.15 on 2026-07-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_paciente_frecuencia_pausa_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alertas',
            field=models.CharField(blank=True, default='', help_text="Alertas clínicas separadas por coma (ej: 'Antecedente de ansiedad, Duelo no elaborado').", max_length=300),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_medicos',
            field=models.TextField(blank=True, default='', help_text='Enfermedades, cirugías, hospitalizaciones relevantes.'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_otros',
            field=models.TextField(blank=True, default='', help_text='Consumo de sustancias u otros antecedentes.'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notas_internas',
            field=models.TextField(blank=True, default='', help_text='Notas internas del equipo (NO son historia clínica: preferencias/avisos del paciente).'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='objetivo_principal',
            field=models.CharField(blank=True, default='', help_text='Objetivo terapéutico principal del proceso.', max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='resumen_clinico',
            field=models.TextField(blank=True, default='', help_text='Resumen del caso (por qué consulta, esquemas, adherencia): para no leer todas las evoluciones.'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='riesgo',
            field=models.CharField(blank=True, choices=[('sin_evaluar', 'Sin evaluar'), ('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], default='', help_text='Nivel de riesgo actual.', max_length=12),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sesiones_proceso',
            field=models.PositiveIntegerField(default=0, help_text="Total estimado del proceso actual (para 'Sesión 8 de 12'). 0 = no fijado.", verbose_name='sesiones del proceso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes',
            field=models.TextField(blank=True, default='', help_text='Antecedentes PSICOLÓGICOS (histórico emocional/clínico del paciente).'),
        ),
    ]
