# Generated by Django 5.2.15 on 2026-07-08 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recurso'),
        ('pacientes', '0018_paciente_alertas_paciente_antecedentes_familiares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('escala', models.CharField(choices=[('phq9', 'PHQ-9 · Depresión'), ('gad7', 'GAD-7 · Ansiedad'), ('dass21', 'DASS-21 · Estrés'), ('isi', 'ISI · Insomnio'), ('pss10', 'PSS-10 · Estrés percibido'), ('pcl5', 'PCL-5 · Estrés postraumático'), ('otra', 'Otra escala')], max_length=12)),
                ('escala_otra', models.CharField(blank=True, default='', help_text="Nombre si la escala es 'Otra'.", max_length=80)),
                ('puntaje', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicación de escala',
                'verbose_name_plural': 'Aplicaciones de escala',
                'ordering': ['fecha', 'id'],
                'indexes': [models.Index(fields=['clinica', 'paciente', 'escala'], name='pacientes_a_clinica_a84445_idx')],
            },
        ),
    ]
