# Generated by Django 5.2.15 on 2026-07-08 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recurso'),
        ('pacientes', '0019_aplicacionescala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(max_length=200)),
                ('progreso', models.PositiveSmallIntegerField(default=0, help_text='Avance 0-100 %.')),
                ('estado', models.CharField(choices=[('activo', 'En curso'), ('logrado', 'Logrado'), ('pausado', 'Pausado')], default='activo', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo terapéutico',
                'verbose_name_plural': 'Objetivos terapéuticos',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['clinica', 'paciente'], name='pacientes_o_clinica_d6a50a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('texto', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('cumplida', 'Cumplida')], default='pendiente', max_length=10)),
                ('fecha', models.DateField(blank=True, help_text='Fecha objetivo/entrega (opcional).', null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'paciente', 'estado'], name='pacientes_t_clinica_1cc061_idx')],
            },
        ),
    ]
