# Generated by Django 5.2.15 on 2026-07-08 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recurso'),
        ('pacientes', '0020_objetivoterapeutico_tarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('psiquiatra', 'Psiquiatra'), ('nutricionista', 'Nutricionista'), ('neurologo', 'Neurólogo'), ('medico', 'Médico'), ('terapeuta', 'Terapeuta'), ('abogado', 'Abogado'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('tipo_otro', models.CharField(blank=True, default='', help_text="Especialidad si el tipo es 'Otro'.", max_length=60)),
                ('nombre', models.CharField(max_length=160)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_profesionales', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_profesionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto profesional',
                'verbose_name_plural': 'Red de profesionales',
                'ordering': ['tipo', 'nombre'],
                'indexes': [models.Index(fields=['clinica', 'paciente'], name='pacientes_c_clinica_b4ce40_idx')],
            },
        ),
    ]
