# Generated by Django 5.2.15 on 2026-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0021_contactoprofesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='brujula_barreras',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='brujula_factores_protectores',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='brujula_factores_riesgo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='brujula_fortalezas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='brujula_hipotesis',
            field=models.TextField(blank=True, default='', verbose_name='hipótesis clínica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='brujula_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='brujula_objetivos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='brujula_plan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
