# Generated by Django 5.2.15 on 2026-07-09 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recurso'),
        ('pacientes', '0022_paciente_brujula_barreras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nps_pendiente_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RespuestaNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('puntaje', models.PositiveSmallIntegerField(help_text='0 a 10.')),
                ('comentario', models.CharField(blank=True, default='', max_length=300)),
                ('fecha', models.DateField()),
                ('origen', models.CharField(choices=[('whatsapp', 'Respondió por WhatsApp'), ('manual', 'Registrado por el equipo')], default='manual', max_length=10)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nps_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta NPS',
                'verbose_name_plural': 'Respuestas NPS',
                'ordering': ['fecha', 'id'],
                'indexes': [models.Index(fields=['clinica', 'paciente'], name='pacientes_r_clinica_3a443a_idx')],
            },
        ),
    ]
