# Generated by Django 5.2.15 on 2026-07-11 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clinica_meta_ideal_mes_clinica_meta_min_mes'),
        ('pacientes', '0023_paciente_nps_pendiente_desde_respuestanps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_consulta',
            field=models.TextField(blank=True, default='', verbose_name='motivo indicado por el consultante'),
        ),
        migrations.CreateModel(
            name='RegistroEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('cita', 'Cita'), ('pago', 'Pago')], max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('paciente_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de eliminación',
                'verbose_name_plural': 'Registros de eliminación',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'creado_en'], name='pacientes_r_clinica_8af3fe_idx')],
            },
        ),
    ]
