# Generated by Django 5.2.15 on 2026-07-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0024_cita_motivo_consulta_registroeliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='categoria',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('adultos', 'Adultos'), ('infantojuvenil', 'Infantojuvenil'), ('parejas', 'Parejas'), ('constancias', 'Constancias e informes')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(blank=True, max_length=120, verbose_name='servicio'),
        ),
    ]
