# Generated by Django 5.2.15 on 2026-08-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0028_consentimiento_aceptado_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='decision',
            field=models.CharField(blank=True, choices=[('DP-01', 'DP-01 · Inicia proceso'), ('DP-02', 'DP-02 · Solicita tiempo para decidir'), ('DP-03', 'DP-03 · Seguimiento posterior'), ('DP-04', 'DP-04 · No inicia proceso'), ('DP-05', 'DP-05 · Evaluación psicológica'), ('DP-06', 'DP-06 · Informe psicológico'), ('DP-07', 'DP-07 · Convenio / Empresa'), ('DP-08', 'DP-08 · Continúa proceso'), ('DP-09', 'DP-09 · Suspende temporalmente / Finaliza proceso'), ('DP-10', 'DP-10 · Alta terapéutica'), ('DP-11', 'DP-11 · Derivación interna'), ('DP-12', 'DP-12 · Derivación externa'), ('DP-13', 'DP-13 · Interconsulta (interna o externa)'), ('DP-14', 'DP-14 · Limitación económica'), ('DP-15', 'DP-15 · Limitación de horario'), ('DP-16', 'DP-16 · Inconformidad con la atención')], db_index=True, default='', max_length=6, verbose_name='decisión del paciente'),
        ),
    ]
