# Generated by Django 5.2.15 on 2026-08-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_alter_egreso_medio_pago'),
        ('pacientes', '0029_cita_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='finanzas.paquete', verbose_name='cubierta por el paquete'),
        ),
    ]
