# Generated by Django 5.2.15 on 2026-08-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0030_cita_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroeliminacion',
            name='tipo',
            field=models.CharField(choices=[('cita', 'Cita'), ('pago', 'Pago'), ('paciente', 'Paciente')], max_length=10),
        ),
    ]
