# Generated by Django 5.2.15 on 2026-09-10 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_clinica_gamificacion'),
        ('pacientes', '0033_cita_decision_trazabilidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionContinuidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('cierre_bloque', 'Cierre de bloque'), ('riesgo_s3', 'Riesgo S3')], max_length=16)),
                ('meta', models.PositiveSmallIntegerField(help_text='Bloque del evento: 3 (riesgo S3), 6, 12, 18, 24…')),
                ('estado_revision', models.CharField(choices=[('sin_revisar', 'Sin revisar'), ('en_seguimiento', 'En seguimiento'), ('resuelto', 'Resuelto')], default='sin_revisar', max_length=16)),
                ('resultado_operativo', models.CharField(blank=True, choices=[('pendiente_real', 'Pendiente real'), ('ya_actualizado', 'Ya actualizado'), ('requiere_correccion', 'Requiere corrección'), ('requiere_confirmar', 'Requiere confirmar')], default='', max_length=24)),
                ('responsable', models.CharField(blank=True, choices=[('coordinacion', 'Coordinación'), ('psicologo', 'Psicólogo'), ('direccion_clinica', 'Dirección Clínica'), ('sistema_soporte', 'Sistema / soporte')], default='', max_length=20)),
                ('observacion_operativa', models.TextField(blank=True, default='', help_text='Solo lo necesario para el seguimiento operativo. No es historia clínica.')),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(blank=True, null=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuidad_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cita_referencia', models.ForeignKey(blank=True, help_text='La cita que representa la condición detectada (S3, la del cierre, o la previa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_continuidad', to='pacientes.cita')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_continuidad', to='pacientes.paciente')),
                ('resuelto_por', models.ForeignKey(blank=True, help_text='Vacío con resuelto_en lleno = la cerró el sistema por cambio en la fuente oficial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuidad_resueltas', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Quien hizo el primer guardado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuidad_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestión de continuidad',
                'verbose_name_plural': 'Gestiones de continuidad',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContinuidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.CharField(choices=[('revision_iniciada', 'Revisión iniciada'), ('estado', 'Estado de revisión'), ('resultado', 'Resultado operativo'), ('responsable', 'Responsable'), ('observacion', 'Observación actualizada'), ('referencia', 'Referencia del evento actualizada'), ('auto_resuelto', 'Condición resuelta automáticamente'), ('reabierto', 'Condición reabierta'), ('nueva_condicion', 'Nueva condición detectada')], max_length=20)),
                ('antes', models.CharField(blank=True, default='', max_length=60)),
                ('despues', models.CharField(blank=True, default='', max_length=60)),
                ('origen', models.CharField(choices=[('usuario', 'Usuario'), ('sistema', 'Sistema')], default='usuario', max_length=8)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.gestioncontinuidad')),
                ('usuario', models.ForeignKey(blank=True, help_text='Vacío en eventos del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_continuidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de continuidad',
                'verbose_name_plural': 'Historial de continuidad',
                'ordering': ['creado_en', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='gestioncontinuidad',
            index=models.Index(fields=['clinica', 'paciente'], name='pacientes_g_clinica_68c901_idx'),
        ),
        migrations.AddIndex(
            model_name='gestioncontinuidad',
            index=models.Index(fields=['clinica', 'estado_revision'], name='pacientes_g_clinica_6bf079_idx'),
        ),
        migrations.AddConstraint(
            model_name='gestioncontinuidad',
            constraint=models.UniqueConstraint(condition=models.Q(('resuelto_en__isnull', True)), fields=('paciente', 'tipo', 'meta'), name='uniq_gestion_continuidad_abierta'),
        ),
        migrations.AddIndex(
            model_name='historialcontinuidad',
            index=models.Index(fields=['clinica', 'gestion'], name='pacientes_h_clinica_187881_idx'),
        ),
    ]
