# Generated by Django 5.2.15 on 2026-09-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0034_gestion_continuidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestioncontinuidad',
            name='resultado_operativo',
            field=models.CharField(blank=True, choices=[('pendiente_real', 'Pendiente real'), ('ya_actualizado', 'Ya actualizado'), ('requiere_correccion', 'Requiere corrección'), ('requiere_confirmar', 'Requiere confirmar'), ('paciente_continua', 'Paciente desea continuar'), ('pausa_temporal', 'Pausa temporal (más adelante)'), ('no_continuara', 'No continuará (cierre administrativo)'), ('sin_respuesta', 'Contactado, sin respuesta')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='historialcontinuidad',
            name='evento',
            field=models.CharField(choices=[('revision_iniciada', 'Revisión iniciada'), ('estado', 'Estado de revisión'), ('resultado', 'Resultado operativo'), ('responsable', 'Responsable'), ('observacion', 'Observación actualizada'), ('referencia', 'Referencia del evento actualizada'), ('auto_resuelto', 'Condición resuelta automáticamente'), ('reabierto', 'Condición reabierta'), ('nueva_condicion', 'Nueva condición detectada'), ('whatsapp_enviado', 'WhatsApp enviado'), ('whatsapp_fallido', 'WhatsApp no se pudo enviar'), ('respuesta_paciente', 'Respuesta del paciente'), ('contacto_bloqueado', 'Contacto bloqueado')], max_length=20),
        ),
    ]
