# Generated by Django 5.2.15 on 2026-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0035_alter_gestioncontinuidad_resultado_operativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcontinuidad',
            name='evento',
            field=models.CharField(choices=[('revision_iniciada', 'Revisión iniciada'), ('estado', 'Estado de revisión'), ('resultado', 'Resultado operativo'), ('responsable', 'Responsable'), ('observacion', 'Observación actualizada'), ('referencia', 'Referencia del evento actualizada'), ('auto_resuelto', 'Condición resuelta automáticamente'), ('reabierto', 'Condición reabierta'), ('nueva_condicion', 'Nueva condición detectada'), ('whatsapp_enviado', 'WhatsApp enviado'), ('whatsapp_fallido', 'WhatsApp no se pudo enviar'), ('respuesta_paciente', 'Respuesta del paciente'), ('contacto_bloqueado', 'Contacto bloqueado'), ('contacto_manual', 'Mensaje copiado (envío manual)')], max_length=20),
        ),
    ]
