# Generated by Django 5.2.15 on 2026-09-16 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('pacientes', '0036_alter_historialcontinuidad_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFusionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('principal_id_original', models.PositiveIntegerField(verbose_name='id del paciente principal')),
                ('secundario_id_eliminado', models.PositiveIntegerField(verbose_name='id del paciente eliminado')),
                ('principal_nombre', models.CharField(max_length=200)),
                ('secundario_nombre', models.CharField(max_length=200)),
                ('motivo', models.TextField(blank=True, default='')),
                ('relaciones_movidas', models.JSONField(blank=True, default=dict)),
                ('campos_heredados', models.JSONField(blank=True, default=list)),
                ('conflictos_resueltos', models.JSONField(blank=True, default=list)),
                ('continuidad_antes', models.JSONField(blank=True, default=dict)),
                ('continuidad_despues', models.JSONField(blank=True, default=dict)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('fusionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusiones_pacientes', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(blank=True, help_text='La ficha que sobrevivió. Vacío solo si después se eliminó.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusiones_recibidas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Registro de fusión de pacientes',
                'verbose_name_plural': 'Registros de fusión de pacientes',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'creado_en'], name='pacientes_r_clinica_526779_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevisionDuplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, default='', max_length=300)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_duplicado_a', to='pacientes.paciente')),
                ('paciente_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_duplicado_b', to='pacientes.paciente')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados_descartados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duplicado descartado',
                'verbose_name_plural': 'Duplicados descartados',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('clinica', 'paciente_a', 'paciente_b'), name='uniq_revision_duplicado_par')],
            },
        ),
    ]
