# Generated by Django 5.2.15 on 2026-10-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0037_registrofusionpaciente_revisionduplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tutor_correo',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo del tutor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor_correo_verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
