# Generated by Django 5.2.15 on 2026-10-01 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('pacientes', '0038_paciente_tutor_correo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_sugerido', models.CharField(choices=[('sin_evaluar', 'Sin evaluar'), ('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], max_length=12)),
                ('fuente', models.CharField(default='eli_nota_voz', max_length=40)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('confirmada', 'Confirmada'), ('modificada', 'Modificada'), ('rechazada', 'Rechazada'), ('reemplazada', 'Reemplazada por una sugerencia más nueva')], db_index=True, default='pendiente', max_length=12)),
                ('valor_final', models.CharField(blank=True, choices=[('sin_evaluar', 'Sin evaluar'), ('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto')], default='', max_length=12)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_riesgo', to='pacientes.atencion')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias_riesgo', to='pacientes.paciente')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
