# Generated by Django 5.2.15 on 2026-06-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Psicólogo/a'), ('asistente', 'Asistente')], default='asistente', max_length=20),
        ),
    ]
