# Generated by Django 5.2.15 on 2026-06-18 15:00

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clinica_token_captacion'),
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('titulo', models.CharField(default='Lic. Psicología', max_length=120)),
                ('colegiatura', models.CharField(blank=True, default='', max_length=40, verbose_name='C.PS.P')),
                ('enfoque', models.TextField(blank=True, default='', help_text='Resumen del enfoque y especialidad.')),
                ('poblaciones', models.CharField(blank=True, default='', help_text='niños, adolescentes, adultos, parejas…', max_length=200)),
                ('problematicas', models.TextField(blank=True, default='')),
                ('formacion', models.TextField(blank=True, default='')),
                ('trayectoria', models.TextField(blank=True, default='')),
                ('sede', models.CharField(choices=[('piura', 'Piura'), ('lima', 'Lima')], default='piura', max_length=10)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('ambas', 'Presencial y virtual')], default='ambas', max_length=12)),
                ('frase', models.CharField(blank=True, default='', max_length=300)),
                ('foto', models.FileField(blank=True, null=True, upload_to=usuarios.models.ruta_foto_profesional)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('usuario', models.OneToOneField(blank=True, help_text='Cuenta de login enlazada (si atiende sesiones en la agenda).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['clinica', 'activo'], name='usuarios_pr_clinica_e53a83_idx')],
            },
        ),
    ]
