# Generated by Django 5.2.15 on 2026-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='horas_disponibles',
            field=models.PositiveIntegerField(default=0, help_text='Cupos de sesión que ofrece a la semana (para la ocupación de agenda).', verbose_name='horas/sesiones disponibles por semana'),
        ),
    ]
