# Generated by Django 5.2.15 on 2026-06-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_profesional_horas_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Psicólogo/a'), ('asistente', 'Asistente'), ('comercial', 'Comercial')], default='asistente', max_length=20),
        ),
    ]
