# Generated by Django 5.2.15 on 2026-06-30 20:18

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_numerowhatsapp'),
        ('usuarios', '0006_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='contrato_estado',
            field=models.CharField(blank=True, choices=[('preparando', 'Preparando'), ('entregado', 'Entregado'), ('firmado', 'Firmado')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='profesional',
            name='contrato_ultima_firma',
            field=models.DateField(blank=True, null=True, verbose_name='última firma'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='contrato_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='vencimiento del contrato'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Desde cuándo está con nosotros (para aniversarios).', null=True, verbose_name='fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('adenda', 'Adenda'), ('otro', 'Otro')], default='contrato', max_length=12)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=usuarios.models.ruta_doc_legal)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_legales', to='usuarios.profesional')),
            ],
            options={
                'verbose_name': 'Documento legal',
                'verbose_name_plural': 'Documentos legales',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
