# Generated by Django 5.2.15 on 2026-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_legal_contratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='horario_semanal',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
