# Generated by Django 5.2.15 on 2026-07-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_profesional_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='porcentaje_liquidacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de lo cobrado en sus sesiones que se le paga al psicólogo (ej: 40 = 40%).', max_digits=5, verbose_name='% de honorarios'),
        ),
    ]
