# Generated by Django 5.2.15 on 2026-07-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_profesional_porcentaje_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sede',
            field=models.CharField(blank=True, choices=[('lima', 'Lima'), ('piura', 'Piura')], default='', max_length=10),
        ),
    ]
