# Generated by Django 5.2.15 on 2026-07-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='horario_modalidad',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
