# Generated by Django 5.2.15 on 2026-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_profesional_horario_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Psicólogo/a'), ('asistente', 'Asistente'), ('comercial', 'Comercial'), ('analista', 'Analista')], default='asistente', max_length=20),
        ),
    ]
