# Generated by Django 5.2.15 on 2026-09-19 14:31

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='video',
            field=models.FileField(blank=True, help_text='Video corto de presentación (máx. 25 MB). Se muestra en su perfil de la web.', null=True, upload_to=usuarios.models.ruta_video_profesional, verbose_name='video de presentación'),
        ),
    ]
