# Generated by Django 5.2.15 on 2026-09-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text="Enlace del video en YouTube (súbelo como 'no listado'). Se ve dentro de la web, sin mandar a nadie a YouTube.", max_length=400, verbose_name='video de presentación'),
        ),
    ]
