# Generated by Django 5.2.15 on 2026-10-01 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('pacientes', '0037_registrofusionpaciente_revisionduplicado'),
        ('usuarios', '0014_remove_profesional_video_url_profesional_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoContinuidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('barrera_externa', 'Barrera externa'), ('percepcion_servicio', 'Percepción del servicio'), ('experiencia', 'Experiencia'), ('operacion', 'Operación'), ('decision_acordada', 'Decisión acordada'), ('otro', 'Otro'), ('desconocido', 'Desconocido')], max_length=24)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('aplica_a_pausa', models.BooleanField(default=False)),
                ('aplica_a_alta', models.BooleanField(default=False)),
                ('aplica_a_abandono', models.BooleanField(default=False)),
                ('aplica_a_cierre', models.BooleanField(default=False)),
                ('aplica_a_cambio_profesional', models.BooleanField(default=False)),
                ('codigos_dp', models.CharField(blank=True, default='', max_length=60)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Motivo de continuidad',
                'verbose_name_plural': 'Motivos de continuidad',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoContinuidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de la S1 según la última reconciliación.')),
                ('fecha_inicio_original', models.DateField(help_text='Fecha de la S1 cuando se detectó el proceso.')),
                ('fin_observado', models.DateField(blank=True, help_text='Última sesión vista al reconciliar (solo para detectar divisiones).', null=True)),
                ('estado', models.CharField(choices=[('sin_registro', 'Sin estado formal'), ('activo', 'Activo'), ('pausa', 'En pausa'), ('alta', 'Alta'), ('abandono', 'Abandono confirmado'), ('cerrado', 'Cerrado por otra decisión')], default='sin_registro', max_length=16)),
                ('fecha_estado', models.DateField(blank=True, null=True)),
                ('frecuencia_esperada', models.CharField(choices=[('no_definida', 'No definida'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('personalizada', 'Personalizada')], default='no_definida', max_length=16)),
                ('intervalo_personalizado_dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requiere_revision', models.CharField(blank=True, choices=[('', '—'), ('fusion_potencial', 'Otro proceso registrado cae en el mismo tramo'), ('division_potencial', 'Tramo nuevo dentro del período de otro proceso'), ('inicio_ambiguo', 'Varios tramos posibles para este proceso'), ('sin_tramo', 'Sus citas ya no forman un proceso')], default='', max_length=24)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cita_inicio', models.ForeignKey(blank=True, help_text='Ancla: la primera sesión del tramo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pacientes.cita')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_continuidad', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Proceso de continuidad',
                'verbose_name_plural': 'Procesos de continuidad',
                'ordering': ['paciente_id', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoContinuidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('inicio_proceso', 'Inicio del proceso'), ('continuacion_confirmada', 'Proceso confirmado como activo'), ('pausa_iniciada', 'Pausa'), ('reactivacion', 'Reactivación'), ('alta', 'Alta'), ('abandono_confirmado', 'Abandono confirmado'), ('cierre', 'Cierre por otra decisión'), ('cambio_profesional', 'Cambio de profesional'), ('cambio_frecuencia', 'Cambio de frecuencia esperada'), ('correccion_motivo', 'Corrección de motivo')], max_length=24)),
                ('estado_anterior', models.CharField(blank=True, choices=[('sin_registro', 'Sin estado formal'), ('activo', 'Activo'), ('pausa', 'En pausa'), ('alta', 'Alta'), ('abandono', 'Abandono confirmado'), ('cerrado', 'Cerrado por otra decisión')], default='', max_length=16)),
                ('estado_nuevo', models.CharField(choices=[('sin_registro', 'Sin estado formal'), ('activo', 'Activo'), ('pausa', 'En pausa'), ('alta', 'Alta'), ('abandono', 'Abandono confirmado'), ('cerrado', 'Cerrado por otra decisión')], max_length=16)),
                ('fecha_efectiva', models.DateField()),
                ('detalle_operativo', models.CharField(blank=True, default='', help_text='Detalle OPERATIVO breve (no es nota clínica). No entra en métricas.', max_length=280)),
                ('fecha_revision', models.DateField(blank=True, help_text='Pausa: fecha tentativa de revisión.', null=True)),
                ('frecuencia_anterior', models.CharField(blank=True, choices=[('no_definida', 'No definida'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('personalizada', 'Personalizada')], default='', max_length=16)),
                ('frecuencia_nueva', models.CharField(blank=True, choices=[('no_definida', 'No definida'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('personalizada', 'Personalizada')], default='', max_length=16)),
                ('intervalo_nuevo_dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('coordinacion', 'Coordinación'), ('gerencia', 'Gerencia'), ('sistema', 'Sistema'), ('importacion', 'Carga histórica')], max_length=12)),
                ('clave_idempotencia', models.CharField(blank=True, max_length=64, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('corrige', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='continuidad.eventocontinuidad')),
                ('profesional_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usuarios.profesional')),
                ('profesional_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usuarios.profesional')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_continuidad', to=settings.AUTH_USER_MODEL)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='continuidad.motivocontinuidad')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='continuidad.procesocontinuidad')),
            ],
            options={
                'verbose_name': 'Evento de continuidad',
                'verbose_name_plural': 'Eventos de continuidad',
                'ordering': ['fecha_efectiva', 'creado_en', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='motivocontinuidad',
            constraint=models.UniqueConstraint(fields=('clinica', 'codigo'), name='uniq_motivo_continuidad_codigo'),
        ),
        migrations.AddIndex(
            model_name='procesocontinuidad',
            index=models.Index(fields=['clinica', 'paciente'], name='continuidad_clinica_b07f57_idx'),
        ),
        migrations.AddIndex(
            model_name='procesocontinuidad',
            index=models.Index(fields=['clinica', 'estado'], name='continuidad_clinica_53d243_idx'),
        ),
        migrations.AddConstraint(
            model_name='procesocontinuidad',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frecuencia_esperada', 'personalizada'), ('intervalo_personalizado_dias__gte', 1), ('intervalo_personalizado_dias__isnull', False), ('intervalo_personalizado_dias__lte', 180)), models.Q(models.Q(('frecuencia_esperada', 'personalizada'), _negated=True), ('intervalo_personalizado_dias__isnull', True)), _connector='OR'), name='proceso_intervalo_solo_personalizada'),
        ),
        migrations.AddIndex(
            model_name='eventocontinuidad',
            index=models.Index(fields=['clinica', 'proceso', 'fecha_efectiva'], name='continuidad_clinica_b647fb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventocontinuidad',
            index=models.Index(fields=['clinica', 'tipo', 'fecha_efectiva'], name='continuidad_clinica_3fb31c_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventocontinuidad',
            constraint=models.UniqueConstraint(condition=models.Q(('clave_idempotencia__isnull', False)), fields=('clinica', 'clave_idempotencia'), name='uniq_evento_continuidad_idempotencia'),
        ),
    ]
