# Generated by Django 5.2.15 on 2026-10-01 18:24

import django.db.models.deletion
"""Fecha de corte del registro formal, fijada sola.

Cada clínica existente recibe como `registro_formal_desde` la fecha en que se
aplica esta migración, es decir, el día del despliegue: los procesos que
empiecen desde ese día nacen ACTIVO; los anteriores, "sin estado formal".
No hay variable de entorno que configurar.
"""
from django.db import migrations, models
from django.utils import timezone


def fijar(apps, schema_editor):
    Clinica = apps.get_model("core", "Clinica")
    Conf = apps.get_model("continuidad", "ConfiguracionContinuidad")
    hoy = timezone.localdate()
    for clinica in Clinica.objects.all():
        Conf.objects.get_or_create(clinica=clinica, defaults={"registro_formal_desde": hoy})


class Migration(migrations.Migration):

    dependencies = [
        ('continuidad', '0002_catalogo_motivos'),
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionContinuidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registro_formal_desde', models.DateField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Configuración de continuidad',
                'verbose_name_plural': 'Configuración de continuidad',
                'constraints': [models.UniqueConstraint(fields=('clinica',), name='uniq_configuracion_continuidad_clinica')],
            },
        ),
        migrations.RunPython(fijar, migrations.RunPython.noop),
    ]
