# Generated by Django 5.2.15 on 2026-09-19 17:32

import django.db.models.deletion
import faro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('leads', '0019_solicitudinstitucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.CharField(max_length=200, verbose_name='institución educativa')),
                ('ciudad', models.CharField(blank=True, default='', max_length=120)),
                ('contacto', models.CharField(blank=True, default='', max_length=200, verbose_name='enlace institucional')),
                ('token', models.CharField(default=faro.models._token_nuevo, editable=False, max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('autorizando', 'Recogiendo autorizaciones'), ('en_curso', 'Aplicación en curso'), ('analizando', 'En análisis'), ('cerrada', 'Informe entregado')], default='preparando', max_length=14)),
                ('matriculados', models.PositiveIntegerField(blank=True, help_text='Total de estudiantes de secundaria de la institución.', null=True, verbose_name='matriculados en secundaria')),
                ('autorizados', models.PositiveIntegerField(default=0, help_text='Apoderados que autorizaron. Sin esto, el estudiante no participa.', verbose_name='con autorización firmada')),
                ('evaluados', models.PositiveIntegerField(default=0, help_text='Estudiantes que completaron el tamizaje. Es lo que se factura.', verbose_name='efectivamente evaluados')),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
                ('fecha_informe', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('solicitud', models.ForeignKey(blank=True, help_text='De qué solicitud nació esta aplicación, si vino de la web.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones', to='leads.solicitudinstitucional')),
            ],
            options={
                'verbose_name': 'Aplicación de Faro',
                'verbose_name_plural': 'Aplicaciones de Faro',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', 'estado'], name='faro_aplica_clinica_f01d0d_idx')],
            },
        ),
    ]
