# Generated by Django 5.2.15 on 2026-09-19 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('faro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='avisar_whatsapp',
            field=models.CharField(blank=True, default='', help_text='Número de la coordinadora que recibe las alertas rojas. Si se deja vacío, las alertas solo aparecen en el panel.', max_length=40, verbose_name='WhatsApp para alertas'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('grado', models.CharField(blank=True, default='', max_length=30)),
                ('seccion', models.CharField(blank=True, default='', max_length=10)),
                ('codigo', models.CharField(blank=True, default='', max_length=40, verbose_name='código del estudiante')),
                ('respuestas', models.JSONField(default=dict)),
                ('completa', models.BooleanField(default=True)),
                ('nivel', models.CharField(default='verde', max_length=6)),
                ('motivos', models.JSONField(default=list)),
                ('phq_total', models.PositiveSmallIntegerField(default=0)),
                ('gad_total', models.PositiveSmallIntegerField(default=0)),
                ('asq_positivo', models.BooleanField(default=False)),
                ('ebipq_rol', models.CharField(blank=True, default='', max_length=24)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='faro.aplicacion')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Respuesta de tamizaje',
                'verbose_name_plural': 'Respuestas de tamizaje',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivos', models.JSONField(default=list)),
                ('aviso', models.CharField(choices=[('pendiente', 'Sin avisar'), ('enviado', 'Aviso enviado'), ('fallido', 'El aviso falló'), ('sin_canal', 'No hay canal configurado')], default='pendiente', max_length=10)),
                ('aviso_detalle', models.CharField(blank=True, default='', max_length=300)),
                ('avisado_en', models.DateTimeField(blank=True, null=True)),
                ('atendida', models.BooleanField(default=False)),
                ('atendida_en', models.DateTimeField(blank=True, null=True)),
                ('acciones', models.TextField(blank=True, default='', help_text='Qué se hizo: entrevista, con quién se habló, qué se acordó y qué derivación.')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_faro', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('respuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta', to='faro.respuesta')),
            ],
            options={
                'verbose_name': 'Alerta de Faro',
                'verbose_name_plural': 'Alertas de Faro',
                'ordering': ['atendida', '-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='respuesta',
            index=models.Index(fields=['aplicacion', 'nivel'], name='faro_respue_aplicac_258e73_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['clinica', 'atendida'], name='faro_alerta_clinica_4338af_idx'),
        ),
    ]
