# Generated by Django 5.2.15 on 2026-09-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faro', '0003_aplicacion_token_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacion',
            name='evaluados',
        ),
    ]
