# Generated by Django 5.2.15 on 2026-09-22 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('faro', '0004_remove_aplicacion_evaluados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.CharField(max_length=200, verbose_name='nombre del estudiante')),
                ('grado', models.CharField(blank=True, default='', max_length=30)),
                ('seccion', models.CharField(blank=True, default='', max_length=10, verbose_name='sección')),
                ('clave', models.CharField(blank=True, default='', editable=False, max_length=240)),
                ('apoderado', models.CharField(max_length=200, verbose_name='nombre del apoderado')),
                ('documento', models.CharField(blank=True, default='', max_length=20, verbose_name='documento de identidad')),
                ('parentesco', models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('apoderado', 'Apoderado o tutor')], default='apoderado', max_length=12)),
                ('correo', models.EmailField(help_text='A esta dirección se envía el resultado individual del estudiante.', max_length=254)),
                ('celular', models.CharField(blank=True, default='', max_length=30)),
                ('autoriza', models.BooleanField(default=False)),
                ('version_texto', models.CharField(blank=True, default='', help_text='Qué versión del texto aceptó. Si el texto cambia, esto dice quién firmó cuál.', max_length=20, verbose_name='versión del consentimiento')),
                ('firmado_en', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('envio_detalle', models.CharField(blank=True, default='', max_length=300)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='faro.aplicacion')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Autorización de Faro',
                'verbose_name_plural': 'Autorizaciones de Faro',
                'ordering': ['estudiante'],
            },
        ),
        migrations.AddField(
            model_name='respuesta',
            name='autorizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='faro.autorizacion'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['aplicacion', 'clave'], name='faro_autori_aplicac_5f8eee_idx'),
        ),
        migrations.AddIndex(
            model_name='autorizacion',
            index=models.Index(fields=['aplicacion', 'autoriza'], name='faro_autori_aplicac_ca06ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='autorizacion',
            constraint=models.UniqueConstraint(fields=('aplicacion', 'clave'), name='faro_una_autorizacion_por_estudiante'),
        ),
    ]
