# Generated by Django 5.2.15 on 2026-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faro', '0006_aplicacion_token_apoderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='ciber_rol',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
