# Generated by Django 5.2.15 on 2026-06-12 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_clinica_whatsapp_instance'),
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio de cita'), ('confirmacion', 'Confirmación'), ('seguimiento', 'Seguimiento'), ('manual', 'Mensaje manual')], default='manual', max_length=20)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Falló'), ('no_configurado', 'Sin WhatsApp')], max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='pacientes.cita')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinica', '-creado_en'], name='mensajes_me_clinica_df7759_idx')],
            },
        ),
    ]
