# Generated by Django 5.2.15 on 2026-06-24 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_metricamensual_leads'),
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('clave', models.CharField(help_text='recordatorio, confirmacion, pago, ubicacion, politicas, consentimiento…', max_length=30)),
                ('nombre', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
            ],
            options={
                'verbose_name': 'Plantilla de mensaje',
                'verbose_name_plural': 'Plantillas de mensaje',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('clinica', 'clave'), name='uniq_plantilla_clave')],
            },
        ),
    ]
