# Generated by Django 5.2.15 on 2026-06-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_plantilla_cumpleanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillamensaje',
            name='wa_template_idioma',
            field=models.CharField(blank=True, default='es', help_text='Código de idioma de la plantilla aprobada (ej. es, es_ES, es_MX).', max_length=10, verbose_name='Idioma de la plantilla'),
        ),
        migrations.AddField(
            model_name='plantillamensaje',
            name='wa_template_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre EXACTO de la plantilla aprobada en Meta WhatsApp Manager.', max_length=120, verbose_name='Plantilla aprobada (Meta)'),
        ),
        migrations.AddField(
            model_name='plantillamensaje',
            name='wa_template_vars',
            field=models.CharField(blank=True, default='', help_text='Variables que llenan {{1}},{{2}}… en orden, separadas por coma. Ej: nombre o nombre,clinica', max_length=200, verbose_name='Variables de la plantilla'),
        ),
    ]
