# Generated by Django 5.2.15 on 2026-09-10 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_clinica_token_webhook_evolution_instanciaevolution'),
        ('mensajes', '0006_mensaje_tipo_automatico'),
        ('pacientes', '0034_gestion_continuidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='direccion',
            field=models.CharField(choices=[('saliente', 'Enviado'), ('entrante', 'Recibido')], default='saliente', max_length=10),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='error_codigo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='external_message_id',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='instancia',
            field=models.CharField(blank=True, default='', help_text='Instancia de Evolution que envió o recibió el mensaje.', max_length=120, verbose_name='Instancia / línea'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='proveedor',
            field=models.CharField(blank=True, choices=[('meta', 'WhatsApp Cloud (Meta)'), ('evolution', 'Evolution API'), ('manual', 'Manual (wa.me)')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='sede',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Falló'), ('no_configurado', 'Sin WhatsApp'), ('recibido', 'Recibido'), ('entregado', 'Entregado'), ('leido', 'Leído')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['clinica', 'external_message_id'], name='mensajes_me_clinica_2e2bdd_idx'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('clinica', 'external_message_id'), name='uniq_mensaje_external_id'),
        ),
    ]
