# Generated by Django 5.2.15 on 2026-09-11 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_clinica_token_webhook_evolution_instanciaevolution'),
        ('mensajes', '0007_mensaje_actualizado_en_mensaje_direccion_and_more'),
        ('pacientes', '0035_alter_gestioncontinuidad_resultado_operativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='gestion_continuidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='pacientes.gestioncontinuidad'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('recordatorio', 'Recordatorio de cita'), ('confirmacion', 'Confirmación'), ('seguimiento', 'Seguimiento'), ('automatico', 'Respuesta automática'), ('continuidad', 'Contacto de continuidad'), ('manual', 'Mensaje manual')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['clinica', 'gestion_continuidad'], name='mensajes_me_clinica_b37aac_idx'),
        ),
    ]
