# Generated by Django 5.2.15 on 2026-09-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0008_mensaje_gestion_continuidad_alter_mensaje_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='plantilla_clave',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='texto_original',
            field=models.TextField(blank=True, default=''),
        ),
    ]
