# Generated by Django 5.2.15 on 2026-09-11 22:31

import django.db.models.deletion
import mensajes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_instanciaevolution_uniq_evolution_sede_activa_and_more'),
        ('mensajes', '0009_mensaje_plantilla_clave_mensaje_texto_original'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='grupo_envio',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Falló'), ('no_configurado', 'Sin WhatsApp'), ('pendiente', 'Pendiente de envío'), ('recibido', 'Recibido'), ('entregado', 'Entregado'), ('leido', 'Leído')], max_length=20),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to=mensajes.models.ruta_material)),
                ('categoria', models.CharField(choices=[('ubicaciones', 'Ubicaciones'), ('horarios', 'Horarios'), ('tarifas', 'Tarifas'), ('pagos', 'Medios de pago'), ('online', 'Sesiones online'), ('politicas', 'Políticas'), ('pacientes', 'Material para pacientes'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('sede', models.CharField(blank=True, default='', max_length=10)),
                ('mime', models.CharField(max_length=40)),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('ancho', models.PositiveSmallIntegerField(default=0)),
                ('alto', models.PositiveSmallIntegerField(default=0)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.clinica')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material de WhatsApp',
                'verbose_name_plural': 'Materiales de WhatsApp',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='mensaje',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='mensajes.material'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['clinica', 'categoria', 'activo'], name='mensajes_ma_clinica_14f113_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['clinica', 'activo'], name='mensajes_ma_clinica_89d1d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('clinica', 'hash'), name='uniq_material_hash'),
        ),
    ]
