# Generated by Django 5.2.15 on 2026-09-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0010_mensaje_grupo_envio_mensaje_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='aceptado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='proveedor_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Falló'), ('no_configurado', 'Sin WhatsApp'), ('pendiente', 'Pendiente de envío'), ('aceptado', 'En camino'), ('recibido', 'Recibido'), ('entregado', 'Entregado'), ('leido', 'Leído')], max_length=20),
        ),
    ]
